### ISSUE TITLE
Cannot assign labels to GCP or Azure connector instances

### ISSUE THREAD

**Issue by felix-melligan** [NetApp/terraform-provider-netapp-cloudmanager#96] opened 2022-04-21 12:26 UTC
Affected: netapp-cloudmanager_connector_gcp, netapp-cloudmanager_connector_azure

Would like implementation close to CVO labelling. E.G:
**Azure:**
azure_tag {
              tag_key = "abcd"
              tag_value = "ABCD"
            }

**GCP:**
gcp_label {
        label_key = "abcd"
        label_value = "ABCD"
      }

This value should be updatable after deployment is complete.

**Comment by lonico** [comment] 2023-01-18 18:44
Released in 22.11.0 for GCP.

**Comment by lonico** [comment] 2023-01-18 19:21
Duplicate of #76 for Azure.

Closing this as this is done for GCP and tracked with #76 for Azure.

**Closed by lonico** 2023-01-18 19:21 UTC
Labels: Jira
