### ISSUE TITLE
CVO deployment fails with custom KMS key

### ISSUE THREAD

**Issue by bryanheo** [NetApp/terraform-provider-netapp-cloudmanager#106] opened 2022-08-02 13:22 UTC
Hello

We have completed NetApp CVO deployment in GCP and we are working on it in AWS.
We deploy NetApp CVO as shown below and if we do not define aws_encryption_kms_key_id, it works ok with the default aws/ebs KMS key but if we define aws_encryption_kms_key_id with our custom key, it returns error below
Could you investigate the issue?

TF code
```
resource "aws_kms_key" "this" {
  description  = "NetApp data encryption key"
  multi_region = true
}

resource "aws_kms_alias" "this" {
  name          = "alias/netapp-data-encryption-key"
  target_key_id = aws_kms_key.this.key_id
}

resource "netapp-cloudmanager_cvo_aws" "this" {
    aws_encryption_kms_key_id     = aws_kms_key.this.id
    backup_volumes_to_cbs         = false
    capacity_package_name         = "Freemium"
    capacity_tier                 = "S3"
    client_id                     = "xxxxx"
    cluster_floating_ip           = "172.xx.xx.1"
    data_encryption_type          = "AWS"
    data_floating_ip              = "172.xx.xx.2"
    data_floating_ip2             = "172.xx.xx.3"
    ebs_volume_size               = 500
    ebs_volume_size_unit          = "GB"
    ebs_volume_type               = "gp3"
    enable_compliance             = false
    enable_monitoring             = false
    failover_mode                 = "FloatingIP"
    id                            = (known after apply)
    instance_tenancy              = "default"
    instance_type                 = "m5.xlarge"
    iops                          = 12000
    is_ha                         = true
    license_type                  = "capacity-paygo"
    mediator_assign_public_ip     = true
    mediator_key_pair_name        = "netapp"
    mediator_subnet_id            = "subnet-xxxxx"
    name                          = "netappusepri"
    node1_subnet_id               = "subnet-xxxxx"
    node2_subnet_id               = "subnet-xxxxx"
    ontap_version                 = "latest"
    optimized_network_utilization = true
    region                        = "us-east-1"
    route_table_ids               = [
        "rtb-xxxxx",
        "rtb-xxxxx",
        "rtb-xxxxx",
        ]
    svm_floating_ip               = "172.xx.xx.4"
    svm_name                      = (known after apply)
    svm_password                  = (sensitive value)
    throughput                    = 125
    tier_level                    = "normal"
    upgrade_ontap_version         = false
    use_latest_version            = true
    vpc_id                        = "vpc-xxxxx"
    workspace_id                  = "workspace-xxxxx"

    aws_tag {
        tag_key   = "iac_managed"
        tag_value = "terraform"
        }

    }
``` 
Error
```
│ Error: Failed to create CVO, error: The following resource(s) failed to create: [HAMediatorInstance]. Instance i-xxx failed to stabilize. Current state: shutting-down. Reason: Client.InternalError: Client error on launch
│ 
│   with module.use1.module.cvos["primary"].netapp-cloudmanager_cvo_aws.this,
│   on ../../../tf-module-aws-netapp/modules/cvo/cvo.tf line 2, in resource "netapp-cloudmanager_cvo_aws" "this":
│    2: resource "netapp-cloudmanager_cvo_aws" "this" {
```

Regards
Moon

**Comment by bryanheo** [comment] 2022-08-05 08:20
Do you have any updates about the issue above?

**Comment by lonico** [comment] 2022-08-05 14:37
Could you try adding a dependency, or if it's not enough a sleep?

**Comment by bryanheo** [comment] 2022-08-06 21:51
Thank you @lonico 
CVO deployment has failed even though the kms key was already created. For the reason, I do not think this issue is related to the dependency. Could you answer the following questions?

1. Could you reproduce the issue in your lab with the code above?
2. Are there any extra IAM policy required on the node and mediator instance profiles? (If yes, it does not make sense because default KMS key is working ok when aws_encryption_kms_key_id is not defined)

Regards
Moon

**Comment by bryanheo** [comment] 2022-08-11 09:51
Do you have any update?

**Comment by bryanheo** [comment] 2022-08-12 09:19
Please see the error copied from Cloud Manager Timeline

```
The following resource(s) failed to create: [HAMediatorInstance]. Instance i-xxxx failed to stabilize. Current state: shutting-down. Reason: Client.InternalError: Client error on launch

  {
  "vsaMetadata": {
    "licenseType": "ha-capacity-paygo",
    "instanceType": "m5.xlarge",
    "capacityPackageName": "Freemium",
    "ontapVersion": "latest",
    "useLatestVersion": true
  },
  "enableCompliance": false,
  "securityGroupId": "sg-xxxxx",
  "name": "netappamtnuse1pri",
  "instanceTenancy": "default",
  "ebsVolumeSize": {
    "size": 1,
    "unit": "TB"
  },
  "awsEncryptionParameters": {
    "kmsKeyId": "mrk-xxxxx"
  },
  "ebsVolumeType": "gp3",
  "vpcId": "vpc-xxxx",
  "capacityTier": "S3",
  "dataEncryptionType": "AWS",
  "svmPassword": "*****",
  "instanceProfileName": "netappamtnuse1pri-cvo-instance-profile",
  "tierLevel": "normal",
  "haParams": {
    "mediatorKeyPairName": "netapp",
    "dataFloatingIP": "172.xx.xx.xx",
    "mediatorAssignPublicIP": true,
    "dataFloatingIP2": "172.xx.xx.xx",
    "failoverMode": "FloatingIP",
    "node2SubnetId": "subnet-xxxx",
    "svmFloatingIP": "172.xx.xx.xx",
    "routeTableIds": [
      "rtb-xxxx",
      "rtb-xxxx",
      "rtb-xxxx"
    ],
    "node1SubnetId": "subnet-xxxx",
    "mediatorInstanceProfileName": "netappamtnuse1pri-mediator-instance-profile",
    "clusterFloatingIP": "172.xx.xx.xx",
    "mediatorSubnetId": "subnet-xxxx"
  },
  "subnetId": "",
  "backupVolumesToCbs": false,
  "enableMonitoring": false,
  "awsTags": [
    {
      "tagKey": "iac_managed",
      "tagValue": "terraform"
    },
    {
      "tagKey": "owner",
      "tagValue": "Foundation"
    },
    {
      "tagKey": "project",
      "tagValue": "netapp"
    },
    {
      "tagKey": "tier",
      "tagValue": "non-prod"
    }
  ],
  "iops": 12000,
  "region": "us-east-1",
  "tenantId": "workspace-xxxx",
  "throughput": 250,
  "IsHA": true,
  "optimizedNetworkUtilization": true
}

```

**Comment by bryanheo** [comment] 2022-08-12 14:33
Does KMS key require policy for NetApp role or user?

**Comment by suhasbshekar** [comment] 2022-08-12 18:56
we cannot reproduce the issue due to lack of permissions here for our account, we are looking into getting permissions here, to reproduce the issue.

**Comment by bryanheo** [comment] 2022-08-15 15:05
@suhasbshekar I can see the policy on the docs but it shows only the policy If the key is in a different AWS account.
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-setting-up-kms.html

Do you have other NetApp docs regarding the encryption key policy for NetApp CVO in the same account?

**Comment by suhasbshekar** [comment] 2022-08-16 16:53
No we dont have other encryption key policy for NetApp CVO in the same account, we are still facing with permission issue to reproduce.

**Comment by edarzi** [comment] 2022-08-17 09:12
need to verify that the mediator has permission to use that key

**Comment by bryanheo** [comment] 2022-08-18 09:29
With the following policy, we have not had any error but I am not sure whether the policy is sufficient for the operation.
Could you check the policy below?

```
data "aws_iam_policy_document" "kms" {
  statement {
    sid       = "EnableIamUserPermissions"
    resources = ["*"]
    actions   = ["kms:*"]

    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::${var.account_id}:root"]
    }
  }

  statement {
    sid       = "AllowAccessForKeyAdministrators"
    resources = ["*"]

    actions = [
      "kms:Create*",
      "kms:Describe*",
      "kms:Enable*",
      "kms:List*",
      "kms:Put*",
      "kms:Update*",
      "kms:Revoke*",
      "kms:Disable*",
      "kms:Get*",
      "kms:Delete*",
      "kms:TagResource",
      "kms:UntagResource",
      "kms:ScheduleKeyDeletion",
      "kms:CancelKeyDeletion",
    ]

    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::${data.aws_caller_identity.this.account_id}:user/tfe-netapp-deploy"]
    }
  }

  statement {
    sid       = "AllowUseOfTheKey"
    resources = ["*"]

    actions = [
      "kms:Encrypt",
      "kms:Decrypt",
      "kms:ReEncrypt*",
      "kms:GenerateDataKey*",
      "kms:DescribeKey",
    ]

    principals {
      type = "AWS"
      identifiers = [
        "arn:aws:iam::${var.account_id}:role/netapp-connector-instance-role",
        "arn:aws:iam::${var.account_id}:role/${var.cluster_name}-mediator-instance-profile-role",
        "arn:aws:iam::${var.account_id}:role/${var.cluster_name}-cvo-instance-profile-role"
      ]
    }
  }

  statement {
    sid       = "AllowAttachmentOfPersistentResources"
    resources = ["*"]

    actions = [
      "kms:CreateGrant",
      "kms:ListGrants",
      "kms:RevokeGrant",
    ]

    condition {
      test     = "Bool"
      variable = "kms:GrantIsForAWSResource"
      values   = ["true"]
    }

    principals {
      type = "AWS"
      identifiers = [
        "arn:aws:iam::${var.account_id}:role/netapp-connector-instance-role",
        "arn:aws:iam::${var.account_id}:role/${var.cluster_name}-mediator-instance-profile-role",
        "arn:aws:iam::${var.account_id}:role/${var.cluster_name}-cvo-instance-profile-role"
      ]
    }
  }
}
```

**Comment by lonico** [comment] 2022-08-18 20:49
Note that this GitHub repo is dedicated to the Terraform Provider.  
I believe you would see the same issue trying to use a custom KMS key in the CloudManager UI.  Which would confirm this is out of scope for this repo.

Documentation issue can be reported directly to the CloudManager team by using the 
Request doc changes link on each doc page.

For instance
https://github.com/NetAppDocs/cloud-manager-cloud-volumes-ontap/issues/new?body=Page%3A%20[Setting%20up%20the%20AWS%20KMS](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-setting-up-kms.html)

**Comment by bryanheo** [comment] 2022-08-18 21:25
@lonico Thank you. I will create a case to the CloudManager team

**Closed** 2022-08-24 14:09 UTC
Labels: documentation, backend
