### ISSUE TITLE
Error Code 504 message while deploying CVO

### ISSUE THREAD

**Issue by shubhammer** [NetApp/terraform-provider-netapp-cloudmanager#130] opened 2022-09-06 09:47 UTC
In between i see while deploying CVO via terraform the deployment fails with below error

netapp-cloudmanager_cvo_aws.mycvo: Still creating... [12m10s elapsed]
netapp-cloudmanager_cvo_aws.mycvo: Still creating... [12m20s elapsed]
netapp-cloudmanager_cvo_aws.mycvo: Still creating... [12m30s elapsed]
netapp-cloudmanager_cvo_aws.mycvo: Still creating... [12m40s elapsed]
netapp-cloudmanager_cvo_aws.mycvo: Still creating... [12m50s elapsed]
netapp-cloudmanager_cvo_aws.mycvo: Still creating... [13m0s elapsed]
netapp-cloudmanager_cvo_aws.mycvo: Still creating... [13m10s elapsed]
╷
│ Error: code: 504, message: 
│ 
│   with netapp-cloudmanager_cvo_aws.mycvo,
│   on CVO.tf line 1, in resource "netapp-cloudmanager_cvo_aws" "mycvo":
│    1: resource "netapp-cloudmanager_cvo_aws" "mycvo" {
│ 
╵

But if i go to my cloud manager i see the CVO gets created.

**Comment by chuyich** [comment] 2022-09-06 17:37
Can this be reproduced? Do you use terraform cloud/enterprise or just run terraform on your laptop terminal? If it's running on your laptop terminal and reproducible, can you do this and share the log with us?
TF_LOG="DEBUG" terraform apply

**Comment by lonico** [comment] 2022-09-06 18:05
This sounds like a duplicate of #116 - which is a Cloud Manager backend issue.
Though I wonder if we could retry on a 504, if we believe this can be a transient issue.  @chuyich Could you check with Eran?

**Comment by shubhammer** [comment] 2022-09-07 02:51
@chuyich I am using terraform on my linux machine . I dont think i can reproduce the issue. I tried the same code around 5 times yesterday on 3 instances it worked fine, on 2 instances it failed.

**Comment by lonico** [comment] 2022-09-08 16:34
We're adding a retry on 504.   This is abit experimental, as we don't control the backend, and we don't know the root cause for now.

**Comment by lonico** [comment] 2022-09-19 18:51
Retries were implemented in 22.9.0.

**Closed by lonico** 2022-09-19 18:51 UTC
Labels: backend, Jira
